### ISSUE TITLE
[RFXCom] Temperature abrove 25,5 are not correctely reported

### ISSUE THREAD

**Issue by Hector47** [myconstellation/constellation-packages#1]
In the plugin RFXCom, in [TemperatureHumiditySensor.cs](https://github.com/myconstellation/constellation-packages/blob/baf365e5c59ea49541dddf32acc6e6f9721689b8/Rfxcom/RfxCom.Core/Packets/TemperatureHumiditySensor.cs#L63) and in [TemperatureSensor.cs](https://github.com/myconstellation/constellation-packages/blob/baf365e5c59ea49541dddf32acc6e6f9721689b8/Rfxcom/RfxCom.Core/Packets/TemperatureSensor.cs#L57) there is an error in the way the temperature is calculated.

The comments on the same lines appear to be the solution to fix this issue.

**Comment by sebastienwarin** [comment]
I commented this code because it doesn't work or me. I think it's related to the firmware! 
My code works perfectly with the firmware 1001 and 1005 !
What's your version ?

**Comment by Hector47** [comment]
I just updated the firmware to the latest version (FW release 433_1005) and still have the same issue: 

You can find the value send from two sensors:
 
1st sensor:
25.1°c
Metadata:
`Type: TemperatureSensors
RawData: 08-50-01-05-0C-01-00-FB-59`

Value:
`{
  "SensorID": 3073,
  "Channel": 1,
  "SequenceNumber": 5,
  "BatteryLevel": 9,
  "SignalLevel": 5,
  "Temperature": 25.1,
  "SubTypeName": "THR128/138, THC138"
}`

2nd sensor:
26.0°c 
Metadata:
`Type: TemperatureHumiditySensors
RawData: 0A-52-01-3F-E3-02-01-04-30-00-79`

Value:
`{
  "SensorID": 29444,
  "Channel": 4,
  "SequenceNumber": 50,
  "BatteryLevel": 9,
  "SignalLevel": 5,
  "Temperature": 0.6,
  "Humidity": 43,
  "Status": "Dry",
  "SubTypeName": "THGN122/123, THGN132, THGR122/228/238/268"
}`
